# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  Build_And_Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Gatsby Pages
        run: yarn install && yarn run build 
      - name: Publish 
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/DataMigrators/datamigrators.github.io.git && npx gh-pages -d public -u "github-actions-bot <support+actions@github.com>" -b main
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

